### ISSUE TITLE
Having a dedicated channel to share sparkle information in

### ISSUE THREAD

**Issue by nearbycoder** [davidcelis/sparkles#7]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Would be great if you could have a channel where all Sparkle information was aggregated to so that others could see the sparkles that were sent as they were coming in, instead of needing to be in the direct channel the Sparkle was given.

**Describe alternatives you've considered**

N/A

**Additional context**

Depending on if you have plans for making Sparkles potentially private and public I could see this not being a great solution for private sparkles where maybe the message is intended more directly for the receiver of the sparkle.

**Comment by davidcelis** [comment]
I love this idea!

**Comment by davidcelis** [comment]
This was merged in #9 and, now that a settings view has been implemented, can actually be used 🎉
